services:
  - type: web
    name: q-A
    env: python
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0"
    pythonVersion: 3.11.4
    autoDeploy: true