services:
  - type: web
    name: q-A
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    runtime: python